### ISSUE TITLE
Could you provide the pretrained models of LightGlue?

### ISSUE THREAD

**Issue by Yzhbuaa** [veichta/IMC-2023#19]
Hello, thank you for your amazing work and detailed report. I tried to run your repo on a custom dataset, but I noticed that there seems no pretrained LightGlue model provided (specifically ALIKED+LightGlue). I suppose the models could possibly be provided in the hloc-1.3-py3-none-any.whl via urls. Thank you!

**Comment by veichta** [comment]
Hi @Yzhbuaa,

You can find our weights in this [kaggle dataset](https://www.kaggle.com/datasets/alexanderveicht/imc-23-weigths). You can refer to [this notebook](https://www.kaggle.com/code/alexanderveicht/imc2023-from-repo/notebook) in order to check where you have to place them.

The ALIKED weights might also be released soon to the official [LightGlue](https://github.com/cvg/LightGlue) repository.
